# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - arelstone
    commit-message:
      prefix: ⬆️

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - arelstone
    commit-message:
      prefix: 👷