name: Pull Request
on:  
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  title:
    name: Ensure that title uses gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/gitmoji@master

  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@master
        with:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
      - run: yarn lint
      - run: yarn test --passWithNoTests
      - run: yarn build