name: Pull Request
on:  
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  title:
    name: Ensure that title uses gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/gitmoji@master

  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      
      - name: Run linting
        run: yarn lint

      - name: Run tests
        run: yarn test --passWithNoTests
      
      - name: Run build
        run: yarn build
