name: Push to master
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@master
        with:
          token: ${{ secrets.GH_AUTH_TOKEN }}
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test --passWithNoTests
      - name: Run build
        run: npm run build
      - name: Publish
        run: npm publish --access public
      - name: Tag and Release
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GH_AUTH_TOKEN }}
          prerelease: false
          title: v${{ steps.extract_version.outputs.version }}
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
